# ===============================================
# Configuración General del Build
# ===============================================
[build]
  publish = "."
  command = ""

# ===============================================
# Configuración de las Funciones Netlify
# ===============================================
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@octokit/rest", "@octokit/auth-app"]

# ===============================================
# Configuración de los Plugins de Netlify
# ===============================================
[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs]

# ===============================================
# Configuración de Cabeceras (incluyendo CSP)
# ===============================================
[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self' data: https://forms.gle;
    script-src 'self' 'unsafe-inline' https://forms.gle;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://forms.gle;
    img-src 'self' data: https://forms.gle;
    font-src 'self' https://fonts.gstatic.com;
    connect-src 'self' https://forms.gle;
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    upgrade-insecure-requests;
    block-all-mixed-content;
  """

# ===============================================
# Redirecciones para las funciones de Netlify
# ===============================================
[[redirects]]
  from = "/verifyPersonal"
  to = "/.netlify/functions/verifyPersonal"
  status = 200

[[redirects]]
  from = "/verifyEAZ"
  to = "/.netlify/functions/verifyEAZ"
  status = 200

[[redirects]]
  from = "/EAZ"
  to = "/.netlify/functions/EAZ"
  status = 200

[[redirects]]
  from = "/sendMail"
  to = "/.netlify/functions/sendMail"
  status = 200

[[redirects]]
  from = "/github-login"
  to = "/.netlify/functions/github-login"
  status = 200

[[redirects]]
  from = "/github-callback"
  to = "/.netlify/functions/github-callback"
  status = 200

# ===============================================
# Regla de Reescritura para la carpeta foot-page
# La he movido al final para evitar conflictos
# ===============================================
[[redirects]]
  from = "/:splat"
  to = "/foot-page/:splat"
  status = 200

# ===============================================
# Página de Error 404 Personalizada
# ===============================================
[[redirects]]
  from = "/*"
  to = "/error404.html"
  status = 404

  from = "/EN/*"
  to = "/error404.html"
  status = 404